server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://restaurant_loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: "nginx-logs"
    static_configs:
      - targets:
          - localhost
        labels:
          job: "nginx"
          __path__: /var/log/nginx/*.log

  - job_name: "restaurant_app-logs"
    docker_sd_configs:
      - host: "unix:///var/run/docker.sock"
    relabel_configs:
      - source_labels: ["__meta_docker_container_name"]
        regex: "restaurant_app"
        action: replace
        target_label: job
      - source_labels: ["__meta_docker_container_log_stream"]
        target_label: stream
      - replacement: "/var/lib/docker/containers/*/*.log"
        target_label: __path__
